### ISSUE TITLE
Org and Bucket values from Url configuration parameter are overwritten

### ISSUE THREAD

**Issue by askrinnik** [PragmaticFlow/NBomber.Sinks.InfluxDB#15]
### Steps to reproduce:
Use settings from the [example](https://github.com/PragmaticFlow/NBomber.Grafana/tree/main/example#sending-data-from-nbomber-tests).
```
{
  "InfluxDBSink": {
    "Url": "http://localhost:8086?org=MyOrg&bucket=NBomber",
    "Token": "N3Z_uUDSQ61qVp93K5dNzH3rbNcKxtphDLrjfS_DcX2cdTr3nR2pOlixGCx6HQ8VI66nqnyztOlPFoWFXoe62Q==",
    "CustomTags": [
      {
        "Key": "environment",
        "Value": "linux"
      }
    ]
  }
}
```

Data are not saved to the InfluxDb database.

There is an error in a log file:
```
2023-11-13 02:10:31.020 -06:00 [WRN] [ThreadId:10] Reporting sink: NBomber.Sinks.InfluxDB failed to save realtime scenario stats
System.ArgumentException: Expecting a non-empty string for 'bucket' parameter. Please specify the bucket as a method parameter or use default configuration at 'InfluxDBClientOptions.Bucket'.
   at InfluxDB.Client.Core.Arguments.CheckNonEmptyString(String value, String name)
   at InfluxDB.Client.BatchWriteOptions..ctor(String bucket, String org, WritePrecision precision)
   at InfluxDB.Client.WriteApiAsync.WritePointsAsync(List`1 points, String bucket, String org, CancellationToken cancellationToken)
   at NBomber.DomainServices.TestHost.ReportingSinks.saveRealtimeStats@40.MoveNext()
```

### A root cause of the issue:
The `Org `and `Bucket` properties are [successfully initialized from the `Url `configuration parameter](https://github.com/PragmaticFlow/NBomber.Sinks.InfluxDB/blob/dev/src/NBomber.Sinks.InfluxDB/InfluxDBSink.cs#L76).
But then they [are overwritten by empty config values](https://github.com/PragmaticFlow/NBomber.Sinks.InfluxDB/blob/dev/src/NBomber.Sinks.InfluxDB/InfluxDBSink.cs#L88).

**Comment by AntyaDev** [comment]
Hi @askrinnik ,

Thanks for your input!
Is this bug reproducible on InfluxDB v2?

**Comment by AntyaDev** [comment]
@askrinnik 
please try this version: 5.0.2-beta.0

**Comment by askrinnik** [comment]
Yes, that works. Thanks a lot!
