### ISSUE TITLE
Add ability to create InfluxDB instance with IMetricsRoot in constuctor

### ISSUE THREAD

**Issue by EvgeniyZviryaka** [PragmaticFlow/NBomber.Sinks.InfluxDB#5]
InfluxDBSink(url: string, dbName: string) =
    let metrics = MetricsBuilder().Report.ToInfluxDb(url, dbName).Build()

Currently, this code is using for creation of new IMetricsRoot. I need another constructor that receives IMetricsRoot as a parameter. It will allow me to use different MetricsBuilder features such as default tags, context, metrics send interval and other.

**Comment by AntyaDev** [comment]
https://github.com/PragmaticFlow/NBomber.Sinks.InfluxDB/blob/master/src/NBomber.Sinks.InfluxDB/InfluxDBSink.fs#L12
